services:
  - type: web
    name: nex-mail
    runtime: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DASHBOARD_PASSWORD
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.9
